{% set name = "kafkit" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kafkit-{{ version }}.tar.gz
  sha256: e372f66e710a344dfc0c370a05974e354dba56ea298c495517e68768b61cfaf5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - fastavro
    - python >={{ python_min }}
    - uritemplate

test:
  imports:
    - kafkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://kafkit.lsst.io
  summary: Kafkit helps you write Kafka producers and consumers in Python with asyncio.
  dev_url: https://github.com/lsst-sqre/kafkit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonathansick
